<?php

if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_601a9f34c575c',
    'title' => 'Feature: Consent Dialog',
    'fields' => array(
      array(
        'key' => 'field_6008840d05b34',
        'label' => 'Beschreibung',
        'name' => '',
        'type' => 'message',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Zeigt einen "Consent-Dialog" / "Zustimmungs-Dialog" beim Betreten der Seite. Ermöglicht Besuchern, optionale Skripte zu laden oder nicht zu laden. Die lokale Einstellung wird per Cookie im Browser des Besuchers gespeichert und kann durch einen manuellen Link auf den Anker <strong>#consent-dialog</strong> erneut aufgerufen werden.

    Für das Content-Blocking müssen Developer manuell Anpassungen machen. Siehe dazu readme.md im Modul "feature-consent-dialog".',
        'new_lines' => 'wpautop',
        'esc_html' => 0,
      ),
      array(
        'key' => 'field_61b1c6443e7dc',
        'label' => 'Consent Dialog aktivieren?',
        'name' => 'feature_consent_dialog_active',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_61b1c53b3e7db',
        'label' => 'Consent Dialog',
        'name' => 'feature_consent_dialog',
        'type' => 'group',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_61b1c6443e7dc',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'layout' => 'block',
        'sub_fields' => array(
          array(
            'key' => 'field_61b06e9719d7e',
            'label' => 'Consent Box',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_6022427bc14c6',
            'label' => 'Stil',
            'name' => 'style',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'popup' => 'Popup',
              'bottom-bar' => 'Bottom Bar',
            ),
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
          ),
          array(
            'key' => 'field_5fd7c22133551',
            'label' => 'Titel',
            'name' => 'title',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_6022427bc14c6',
                  'operator' => '==',
                  'value' => 'popup',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Wir benötigen Ihre Zustimmung',
            'placeholder' => 'Wir benötigen Ihre Zustimmung',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5fd7c23733552',
            'label' => 'Intro',
            'name' => 'intro',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Wir verwenden Cookies und Skripte um die Benutzung der Website so optimal wie möglich zu gestalten.',
            'placeholder' => 'Wir verwenden Cookies und Skripte um die Benutzung der Website so optimal wie möglich zu gestalten.',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => '',
          ),
          array(
            'key' => 'field_5fd7c4659155b',
            'label' => 'Info-Link',
            'name' => 'link',
            'type' => 'link',
            'instructions' => 'z.B.: Datenschutz-Seite',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_61b72acb25fff',
            'label' => 'Text "Alle ablehnen" Button',
            'name' => 'consent_none',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_6022427bc14c6',
                  'operator' => '==',
                  'value' => 'popup',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Alle ablehnen',
            'placeholder' => 'Alle ablehnen',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5fd7e315e934c',
            'label' => 'Text "Auswahl zustimmen" Button',
            'name' => 'consent_selection',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_6022427bc14c6',
                  'operator' => '==',
                  'value' => 'popup',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Auswahl zustimmen',
            'placeholder' => 'Auswahl zustimmen',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5fd7e28ee934b',
            'label' => 'Text "Allen zustimmen" Button',
            'name' => 'consent_all',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Allen zustimmen',
            'placeholder' => 'Allen zustimmen',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_61b72f3eaf295',
            'label' => 'Text "Zustimmung anpassen" Link',
            'name' => 'consent_setup',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_6022427bc14c6',
                  'operator' => '==',
                  'value' => 'popup',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Zustimmung anpassen',
            'placeholder' => 'Zustimmung anpassen',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5fec509bd5f49',
            'label' => 'Cookie-Gültigkeit',
            'name' => 'expire',
            'type' => 'number',
            'instructions' => 'Nach wie vielen Tagen soll der Benutzer erneut um Zustimmung gebeten werden?',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 30,
            'placeholder' => 30,
            'prepend' => '',
            'append' => 'Tage',
            'min' => '',
            'max' => '',
            'step' => '',
          ),
          array(
            'key' => 'field_61b06ead19d7f',
            'label' => 'Consent-Gruppen',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_6022427bc14c6',
                  'operator' => '==',
                  'value' => 'popup',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_61b088e3d27f8',
            'label' => 'Infotext "Essentielles"',
            'name' => 'essential_text',
            'type' => 'textarea',
            'instructions' => 'Erscheint unter der Auswahl und kann per Shortcode [consent_dialog_infotext type="external"] ausgegeben werden.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Essentielle Funktionen der Website. Enthält keine externen Skripte.',
            'placeholder' => 'Essentielle Funktionen der Website. Enthält keine externen Skripte.',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_5fd7e7f943385',
            'label' => 'Externe Medien vorhanden?',
            'name' => 'external_active',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_5fd7d8bc149b6',
            'label' => 'Skripte "Externe Medien"',
            'name' => 'external_scripts',
            'type' => 'textarea',
            'instructions' => 'Wird je nach Benutzer-Auswahl asynchron nachgeladen und automatisch im html-head mit script-Tag umschlossen ausgegeben.',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5fd7e7f943385',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 6,
            'new_lines' => '',
          ),
          array(
            'key' => 'field_61b06f9519d82',
            'label' => 'Infotext "Externe Medien"',
            'name' => 'external_text',
            'type' => 'textarea',
            'instructions' => 'Erscheint unter der Auswahl und kann per Shortcode [consent_dialog_infotext type="external"] ausgegeben werden.',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5fd7e7f943385',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Wir verwenden eingebettete Inhalte von YouTube & GoogleMaps.',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_61b096664c6d6',
            'label' => 'Blocked-Nachricht "Externe Medien"',
            'name' => 'external_blocked',
            'type' => 'textarea',
            'instructions' => 'Kann über consent_dialog_blocked(\'external\') per PHP ausgegeben werden.',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5fd7e7f943385',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Diese Funktion erfordert die Zustimmung zu "Externe Medien" im Consent Dialog.',
            'placeholder' => 'Diese Funktion erfordert die Zustimmung zu "Externe Medien" im Consent Dialog.',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_61b06f1d19d80',
            'label' => 'Tracking-Skripte vorhanden?',
            'name' => 'tracking_active',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_61b07220aa4ae',
            'label' => 'Skripte "Tracking"',
            'name' => 'tracking_scripts',
            'type' => 'textarea',
            'instructions' => 'Wird je nach Benutzer-Auswahl asynchron nachgeladen und automatisch im html-head mit script-Tag umschlossen ausgegeben.',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_61b06f1d19d80',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 6,
            'new_lines' => '',
          ),
          array(
            'key' => 'field_61b07267aa4af',
            'label' => 'Infotext "Tracking"',
            'name' => 'tracking_text',
            'type' => 'textarea',
            'instructions' => 'Erscheint unter der Auswahl und kann per Shortcode [consent_dialog_infotext type="tracking"] ausgegeben werden.',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_61b06f1d19d80',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Wir erfassen Besucherstatistiken über XYZ.',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_61b096914c6d7',
            'label' => 'Blocked-Nachricht "Tracking"',
            'name' => 'tracking_blocked',
            'type' => 'textarea',
            'instructions' => 'Kann über consent_dialog_blocked(\'tracking\') per PHP ausgegeben werden.',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_61b06f1d19d80',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Diese Funktion erfordert die Zustimmung zu "Tracking" im Consent Dialog.',
            'placeholder' => 'Diese Funktion erfordert die Zustimmung zu "Externe Medien" im Consent Dialog.',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_61b06f4319d81',
            'label' => 'Marketing-Skripte vorhanden?',
            'name' => 'marketing_active',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_61b072ccaa4b0',
            'label' => 'Skripte "Marketing"',
            'name' => 'marketing_scripts',
            'type' => 'textarea',
            'instructions' => 'Wird je nach Benutzer-Auswahl asynchron nachgeladen und automatisch im html-head mit script-Tag umschlossen ausgegeben.',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_61b06f4319d81',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 6,
            'new_lines' => '',
          ),
          array(
            'key' => 'field_61b072efaa4b1',
            'label' => 'Infotext "Marketing"',
            'name' => 'marketing_text',
            'type' => 'textarea',
            'instructions' => 'Erscheint unter der Auswahl und kann per Shortcode [consent_dialog_infotext type="marketing"] ausgegeben werden.',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_61b06f4319d81',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'Wir verwenden Skripte folgender Anbieter, um Ihnen die Funktionen XYZ und ZYX zu ermöglichen.',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_61b097054c6d8',
            'label' => 'Blocked-Nachricht "Marketing"',
            'name' => 'marketing_blocked',
            'type' => 'textarea',
            'instructions' => 'Kann über consent_dialog_blocked(\'marketing\') per PHP ausgegeben werden.',
            'required' => 1,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_61b06f4319d81',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => 'Diese Funktion erfordert die Zustimmung zu "Marketing" im Consent Dialog.',
            'placeholder' => 'Diese Funktion erfordert die Zustimmung zu "Marketing" im Consent Dialog.',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => 'br',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'feature-consent-dialog',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
  ));

  endif;
